resource_group_name      = "apmm-demo-rg"
resource_group_location  = "West Europe"
app_service_plan_name    = "apmm-demo-service-plan"
function_app_name        = "apmm-demo-functions"
application_insight_name = "appmm-app-insight"
